### ISSUE TITLE
Error exceprion when run monitor:run

### ISSUE THREAD

**Issue by DonnieDrummer** [ericmakesstuff/laravel-server-monitor#5]
Argument 1 passed to EricMakesStuff\ServerMonitor\Commands\RunCommand::EricMakesStuff\ServerMonitor\Commands{closure}() must be an instance of EricMakesStuff\Server  
  Monitor\Monitors\BaseMonitor, instance of Illuminate\Support\Collection given, called in /Users/donnie/Projects/wiz.dev/vendor/laravel/framework/src/Illuminate/Suppo  
  rt/Collection.php on line 135 and defined

**Comment by eblount** [comment]
What version of Laravel? Can you post your config/server-monitor.php file?

**Comment by DonnieDrummer** [comment]
Laravel 5.2
Config file is default, i'm only change url's

**Comment by eblount** [comment]
I want to help, but I need more info.

I just did a clean install:

``` bash
laravel new monitor
cd monitor
composer require ericmakesstuff/laravel-server-monitor
[edit config/app.php to add Service Provider]
php artisan vendor:publish --provider="EricMakesStuff\ServerMonitor\ServerMonitorServiceProvider"
[edit config/server-monitor.php to change URLs]
php artisan monitor:run
tail storage/logs/laravel.log
```

And in the log file, I see:

``` bash
[2016-04-06 16:21:04] local.INFO: Disk Usage on Production is Healthy at 35.59% Used: Disk Usage is healthy on Production. Filesystem /home/vagrant/projects/test/monitor is okay: 35.59%  
[2016-04-06 16:21:04] local.INFO: HTTP Ping Success: http://www.mydomain.com/: HTTP Ping Succeeded for http://www.mydomain.com/. Response Code 200.
[2016-04-06 16:21:05] local.INFO: SSL Certificate Valid: https://www.mydomain.com/: SSL Certificate is valid for https://www.mydomain.com/. Expires in 43 days.
```

Version is Laravel Framework version 5.2.29. I have it installed in two other projects, and both are the same version.

Try a composer update to get the latest Laravel 5.2 version? Any other Laravel packages that might be conflicting?

**Comment by DonnieDrummer** [comment]
Sorry, i make mistake in my prev. message. I use Laravel 5.1.

```
composer require ericmakesstuff/laravel-server-monitor
Add service provider
Publish and edit config where change only URLs
```

than make php artisan monitor:run and get exception

[ErrorException]  
  Argument 1 passed to EricMakesStuff\ServerMonitor\Commands\RunCommand::EricMakesStuff\ServerMonitor\Commands{closure}() must be an instance of EricMakesStuff\Server  
  Monitor\Monitors\BaseMonitor, instance of Illuminate\Support\Collection given, called in /Users/donnie/Projects/wiz.dev/vendor/laravel/framework/src/Illuminate/Suppo  
  rt/Collection.php on line 135 and defined

**Comment by eblount** [comment]
There are apparently differences in the Laravel Collection::flatten() method between Laravel 5.1 and 5.2. I've just tagged a new version that does not rely on flatten, and I've tested it on Laravel 5.1. If you do a `composer update`, you should get the update. Please let me know whether this works for you.

**Comment by DonnieDrummer** [comment]
Thanks, this it work)
