### ISSUE TITLE
Monitor Disk Space On External Server

### ISSUE THREAD

**Issue by karlmonson** [ericmakesstuff/laravel-server-monitor#7]
This is a great package which I plan to use in my projects, I am wondering if it is possible to monitor the disk space usage on an external server, such as a database server? Thanks!

**Comment by eblount** [comment]
I'd think we could do that over SSH - I'll consider writing a monitor for it, or you can always submit a pull request.

For now, though, can the external server run PHP? If so, I'd just start a fresh Laravel project on it somewhere, install and configure this package, and set up a cron job to run `php artisan monitor:run` every day.

To be clear: you wouldn't even need to serve the project over the web; it could sit in any directory and be run only via command line/cron, and you'd still get all of the email/Slack/Pushover notifications.

**Comment by eblount** [comment]
Idea for external server disk space monitoring added to README. Thanks!
