### ISSUE TITLE
Mails not send when using Mailgun as mail driver

### ISSUE THREAD

**Issue by renege** [ericmakesstuff/laravel-server-monitor#8]

**Comment by eblount** [comment]
Seems to be working fine for me, using my Mailgun account.

Here's my .env setup in the Laravel project (with domain/key changed):
MAIL_DRIVER=mailgun
MAIL_HOST=192.168.10.10
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAILGUN_DOMAIN=sandbox123456789123456789123456789.mailgun.org
MAILGUN_SECRET=key-123456789123456789123456

Please let me know what errors you're getting when you try.

**Comment by eblount** [comment]
Let me know if you're still having trouble. I'll close this issue tomorrow if I don't get more information. Thanks.
